-- =========================================================
-- ALVOXIS — privileges + Row Level Security
--
-- The browser (anon / authenticated) may only READ its own
-- rows. Orders, contributions, payment states and gifts are
-- written exclusively by Edge Functions using the service
-- role. The only writes a signed-in user can make are:
--   · their own profile's display_name / avatar_url
--   · their own gift photo, through set_gift_photo() /
--     clear_gift_photo(), which validate everything.
-- =========================================================

alter table public.profiles              enable row level security;
alter table public.orders                enable row level security;
alter table public.order_items           enable row level security;
alter table public.support_contributions enable row level security;
alter table public.gifts                 enable row level security;
alter table public.stripe_events         enable row level security;

-- start from nothing, then grant the minimum
revoke all on table
  public.profiles, public.orders, public.order_items,
  public.support_contributions, public.gifts, public.stripe_events
from anon, authenticated;

revoke all on sequence public.order_number_seq from anon, authenticated;

grant select on table
  public.profiles, public.orders, public.order_items,
  public.support_contributions, public.gifts
to authenticated;

grant update (display_name, avatar_url) on table public.profiles to authenticated;

grant all on table
  public.profiles, public.orders, public.order_items,
  public.support_contributions, public.gifts, public.stripe_events
to service_role;

grant usage, select on sequence public.order_number_seq to service_role;


-- ---------------------------------------------------------
-- policies
-- ---------------------------------------------------------

create policy "profiles: owner can read"
  on public.profiles for select to authenticated
  using ((select auth.uid()) = id);

create policy "profiles: owner can update"
  on public.profiles for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy "orders: owner can read"
  on public.orders for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "order_items: owner can read"
  on public.order_items for select to authenticated
  using (exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
      and o.user_id = (select auth.uid())
  ));

create policy "support_contributions: owner can read"
  on public.support_contributions for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "gifts: owner can read"
  on public.gifts for select to authenticated
  using ((select auth.uid()) = user_id);

-- stripe_events: RLS on, no policies — service role only.


-- ---------------------------------------------------------
-- gift photo — the only gift fields a user may change
-- ---------------------------------------------------------

create or replace function public.set_gift_photo(p_gift_id uuid, p_path text)
returns public.gifts
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid  uuid := auth.uid();
  v_gift public.gifts;
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  select * into v_gift
  from public.gifts
  where id = p_gift_id and user_id = v_uid
  for update;

  if not found then
    raise exception 'gift_not_found' using errcode = 'P0002';
  end if;

  if v_gift.production_status <> 'not_started' or v_gift.photo_status = 'approved' then
    raise exception 'gift_locked' using errcode = 'P0001';
  end if;

  -- path must be <user_id>/<gift_id>/<uuid>.<ext> — generated by the client, never the original filename
  if p_path is null
     or p_path !~ ('^' || v_uid::text || '/' || v_gift.id::text || '/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp)$') then
    raise exception 'invalid_path' using errcode = '22023';
  end if;

  if not exists (
    select 1 from storage.objects o
    where o.bucket_id = 'gift-photos' and o.name = p_path
  ) then
    raise exception 'photo_missing' using errcode = 'P0002';
  end if;

  update public.gifts
  set photo_path = p_path, photo_status = 'uploaded'
  where id = v_gift.id
  returning * into v_gift;

  return v_gift;
end;
$$;

create or replace function public.clear_gift_photo(p_gift_id uuid)
returns public.gifts
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid  uuid := auth.uid();
  v_gift public.gifts;
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  select * into v_gift
  from public.gifts
  where id = p_gift_id and user_id = v_uid
  for update;

  if not found then
    raise exception 'gift_not_found' using errcode = 'P0002';
  end if;

  if v_gift.production_status <> 'not_started' or v_gift.photo_status = 'approved' then
    raise exception 'gift_locked' using errcode = 'P0001';
  end if;

  update public.gifts
  set photo_path = null, photo_status = 'pending'
  where id = v_gift.id
  returning * into v_gift;

  return v_gift;
end;
$$;

revoke all on function public.set_gift_photo(uuid, text) from public, anon;
revoke all on function public.clear_gift_photo(uuid) from public, anon;
grant execute on function public.set_gift_photo(uuid, text) to authenticated;
grant execute on function public.clear_gift_photo(uuid) to authenticated;

-- internal helpers are not callable from the API
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.set_updated_at() from public, anon, authenticated;
